dist: xenial
language: python
python:
  - "3.7"


# safelist
branches:
  only:
    - staging
    # - evol0042

# Install pipenv then run it to install Pipfile dependencies
before_script:
  - pip install pipenv
  - pipenv install

env: DJANGO_SETTINGS_MODULE="goodfat.settings.travis"

services:
  - postgresql

script:
  - python manage.py test