# Generated by Django 2.2.1 on 2019-05-03 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('used', models.BooleanField(verbose_name='Sélectionnée')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(null=True)),
                ('nutrition_score', models.IntegerField()),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('img_url', models.URLField(null=True)),
                ('off_url', models.URLField()),
                ('sugars', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sugars_unit', models.CharField(max_length=5, null=True)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('calcium_unit', models.CharField(max_length=5, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('fat_unit', models.CharField(max_length=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Category')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Product')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='purbeurre.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.AddConstraint(
            model_name='userproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'substitute'), name='substitut_unique'),
        ),
    ]
