# Generated by Django 2.2.1 on 2019-05-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='None yet retreived', max_length=50),
            preserve_default=False,
        ),
    ]
